version: '3.1'

services:
  db:
    image: library/postgres:12
    restart: always
    ports:
      -  '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: triz
